### ISSUE TITLE
The debug of the oppo mobile phone can run normally, but the release crashes

### ISSUE THREAD

**Issue by xxqwf** [transistorsoft/flutter_background_geolocation#1023]
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/57884068/234436520-9b832c1d-4e6d-4b18-88a9-af2f9f45a36f.png">

**Comment by christocracy** [comment]
Ignored issue template.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
