### ISSUE TITLE
Location freeze

### ISSUE THREAD

**Issue by Sardor-art** [transistorsoft/flutter_background_geolocation#1162]
We have purchased a license to use this library on Android. But this library did not work as expected for us. The point is that the location has not changed during the tracking. Who should I ask to fix this error, and it is a similar error to the one we got when we used FusedLocation.

Device type e.x: Samsung (SM-T220)

**Comment by christocracy** [comment]
The issue template is not optional, it's **required**.  

!--
*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************
-->


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
