### ISSUE TITLE
Cannot read properties of undefined (reading 'latitude')

### ISSUE THREAD

**Issue by hafeezrana** [transistorsoft/flutter_background_geolocation#1258]
It was working fine but when I tried to upload this to transistor soft too including my own server ,then it throwing this error.

`HttpEvent {success: false, status: 500, responseText: {"error":"Cannot read properties of undefined (reading 'latitude')"}}`

**Comment by christocracy** [comment]
Please do not ignore the issue template.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
