### ISSUE TITLE
app not setup in Samsung device because warning by Samsung health how to solve this ?  how to turn off connected with health app because i use package in track location only?

### ISSUE THREAD

**Issue by AbdullahAhmed1991998** [transistorsoft/flutter_background_geolocation#1344]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
What is a “warning by Samsung health”?

the plug-in implements the Motion API, which the plug-in uses to toggle location services ON/OFF when the device is detected to be in-motion/still.  The Motion API (which this plug-in has implemented for the last 10 years), has since Android 13, been placed under the umbrella of “Health API”.

read the wiki here “Philosophy of Operation”.

also see my blog:  https://transistorsoft.medium.com/google-play-store-required-declarations-for-foreground-services-and-health-97da6e2abd5a

**Comment by AbdullahAhmed1991998** [comment]
ok now i turn of Philosophy of Operation on android by edit in manifest file 
how turn off in ios ?

**Comment by christocracy** [comment]
Are you aware of the consequences?

**Comment by AbdullahAhmed1991998** [comment]
yes
how to turn off connected with health app because i use package in track location only ?

**Comment by christocracy** [comment]
Do you understand that the plug-in will take much longer on Android to initiate location-tracking without the Motion api as a trigger?

see api docs Config.disableMotionActivityUpdates
