### ISSUE TITLE
Can not track location in background mode in ios from 17.7 to latest?

### ISSUE THREAD

**Issue by pogenz45** [transistorsoft/flutter_background_geolocation#1364]
when i update ios to version 17.7.1, my app not track location in background anymore. same issue of version 18.0.0 or 18.0.1

**Comment by christocracy** [comment]
This issue template is not optional:




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
