### ISSUE TITLE
Foreground notification in release on Android?

### ISSUE THREAD

**Issue by domons** [transistorsoft/flutter_background_geolocation#206]
Hi,
I think about buy a license but I have a question about Android.
Is there a foreground notification in the release version or can it be hidden?

And if I close the application from the app manager, is the task still working?

**Comment by christocracy** [comment]
The notification is required by the os for foreground services.  Without a foreground-service, aggressive background tracking is impossible.

If a location only every 500-1000 meters is sufficient, `useSignificantChangesOnly: true`.  Otherwise, you must accept the notification.  There’s absolutely **no** other way.
