### ISSUE TITLE
Is there a possibility to disable location data sending to Firebase

### ISSUE THREAD

**Issue by Navinmedia** [transistorsoft/flutter_background_geolocation#479]
We are using the plugin to monitor only geofence events. So location data is irrelevant to us.
Is there a possibility to disable Firebase writes to "locations" collection?

**Comment by christocracy** [comment]
See api docs Config.persistMode.

Also see api docs "Geofencing Guide" and method `startGeofences`

**Comment by christocracy** [comment]
Since you've ignored the issue template, I have no idea whether you're talking about iOS or Android.  **Never** ignore the issue template:

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
