### ISSUE TITLE
setOdometer(0) async time question

### ISSUE THREAD

**Issue by aaronsamkennedy** [transistorsoft/flutter_background_geolocation#558]
Very simple, is anyone else having this function take an unordinary long time to finish?
-->
## Your Environment
* Plugin version:'^1.9.0'
* Platform: iOS
* OS version:14.4.2
* Device manufacturer / model:iPhone 12

## Expected Behavior
I have tried multiple different configurations but reverted to the one in the example on pub dev, setting the odometer to 0 when stopping location tracking. 

## Actual Behavior
It takes nearly two minutes for the async setOrdometer(0) function to run. It does not produce any errors and acts as expected.

**Comment by christocracy** [comment]
Are you executing this while *indoors*?  The plugin requests *3* location samples in order to record the most accurate possible location where the odometer was zeroed.  The plugin is likely attempting to connect with GPS satellites.

If you execute this *outdoors*, with a clear view of the sky, it will likely be *much* quicker.
