### ISSUE TITLE
problem local notification not work properly with this plugin

### ISSUE THREAD

**Issue by bardoun7894** [transistorsoft/flutter_background_geolocation#579]
problem local notification not work properly with this plugin .
when i  start plugin  i need after a odometer 100 metre to show local push notification and stop background location  with
 bg.BackgroundGeolocation.stop();  its work fine but after i restart the plugin the some notification shown again and all early notification that i set why is that  . also when i remove the notification its not gone ,

please help to not shown the previous notification work after start background location thanks

**Comment by christocracy** [comment]
Do **not** ignore the issue template.

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
