### ISSUE TITLE
type 'Null' is not a subtype of type 'FutureOr<Location>'

### ISSUE THREAD

**Issue by FirdousNath** [transistorsoft/flutter_background_geolocation#588]
## Error in Crashlytics 

 ```
 Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'Null' is not a subtype of type 'FutureOr<Location>'. Error thrown null.
       at ._completeOnAsyncError(.java)
       at BackgroundGeolocation.setOdometer(BackgroundGeolocation.java)
```

## Your Environment
* Plugin version: ^4.0.2
* Platform:  Android
* OS version: 10+
* Device manufacturer / model: Samsung, Xiomi etc
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(bg.Config(
          locationAuthorizationRequest: 'Always',
          backgroundPermissionRationale: bg.PermissionRationale(
              title:
                  "Allow {applicationName} to access to this device's location in the background?",
              message:
                  "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
              positiveAction: "Change to {backgroundPermissionOptionLabel}",
              negativeAction: "Cancel"),
          triggerActivities:
              'on_foot, walking, running, in_vehicle, on_bicycle',
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          disableElasticity: true,
          distanceFilter: 25,
          speedJumpFilter: 300,
          stopOnTerminate: false,
          startOnBoot: true,
          stopTimeout: 14,
          notification: bg.Notification(
              smallIcon: "drawable/wynd_logo",
              title: "Activity in progress",
              text:
                  "wynd is accessing your location for ride insights and stats"),
          //ios
          preventSuspend: true,
          //heartbeatInterval: 60,
        ));
```

## Context
I think when I call get current location or when dispose is called, this error is being watched on Crashlytics console
`@override
  void dispose() {
    super.dispose();
    bg.BackgroundGeolocation.setOdometer(0.0).catchError((error) {});
  }`

**Comment by christocracy** [comment]
Thanks, I'm looking into this.

**Comment by FirdousNath** [comment]
same config gives one more error 

`Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ef21c8b u0 com.av.wynd/com.transistorsoft.locationmanager.service.ActivityRecognitionService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

**Comment by christocracy** [comment]
>type 'Null' is not a subtype of type 'FutureOr<Location>'

I cannot reproduce this error.  Please create a simple *Hello World* app that reproduces the error, along with reproduction steps.

>Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService()

This is a [well-known issue for all Android developers](https://www.google.com/search?q=Context.startForegroundService()+did+not+then+call+Service.startForeground()&rlz=1C5CHFA_enCA816CA816&oq=Context.startForegroundService()+did+not+then+call+Service.startForeground()&aqs=chrome..69i57j0l3.380j0j7&sourceid=chrome&ie=UTF-8) and is not specifically caused by the plugin.  Android apps have a finite amount of time (10 seconds, I think) to call `Context.startForeground`.  Your app is blocking the main-thread, preventing the plugin from calling `Context.startForeground` on its services.

You must boot your app with *Android [StrictMode](https://developer.android.com/reference/android/os/StrictMode)* enabled in order to see where your app is blocking the main-thread.

In the past, I have meticulously used `StrictMode` to ensure the plugin does not block the main-thread.  Any other reports of this are due to your own application code / third-party dependencies you're using.

The published *Sample App* on Play Store reports no crashes or ANR in the past 60 days.

![](https://dl.dropbox.com/s/nbcdar2vvl59xpi/Screen%20Shot%202021-07-12%20at%2010.18.31%20AM.png?dl=1)

**Comment by christocracy** [comment]
See the [/example](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/src/main/java/com/transistorsoft/flutterbackgroundgeolocationexample/Application.java#L17-L33) app's `Application.java` to learn how to enable `StrictMode`.

To use a custom `Application.java`, you must modify your [AndroidManifest](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/src/main/AndroidManifest.xml#L17)

**Comment by FirdousNath** [comment]
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'Null' is not a subtype of type 'FutureOr<Location>'. Error thrown null.
      at ._completeOnAsyncError(.java)
      at BackgroundGeolocation.setOdometer(BackgroundGeolocation.java)

```

This issue is caused  when `BackgroundGeolocation.setOdometer` is called  when location permission are denied. I have added try catch block and it woks fine now :)
