### ISSUE TITLE
Outdated dependencies for Android

### ISSUE THREAD

**Issue by grahamsmith** [transistorsoft/flutter_background_geolocation#606]
Sorry for abandoning the template but it was not very relevant to the issue. I have noticed a lot of the Android dependencies are **very** outdated e.g. OkHttp is at version 3 but version 4 has been out quite a while, with version 5 in beta.

This is leading to the usual problems with not keeping dependencies up to date, including relying on JCenter being closed and various improvements and security patches etc. I would not expect bleeding edge versions but being in a relatively new version would be expected I think.

I am happy to help on this issue as a long time Android dev as this package is core to some work we are trying to deliver, as well as a paying customer for the product.

**Comment by grahamsmith** [comment]
Some useful notes:

|  Dependency  | lib version | latest version |
| ------------- | ------------- | ------------- |
| OkHTTP3  | 3.12.1 | 3.14.9 (released 2020-05-17) however version 5 is in beta |
| GreenRobot EventBus  | 3.0.0 | 3.2.0 (released 12th Feb 2020) |
| Android Permissions | 0.1.8 | 2.0.54 (released 10th Apr 2020) |
| SLF4J | 1.7.25 | 1.7.32 ([released 1st July 2021](https://mvnrepository.com/artifact/org.slf4j/slf4j-api) NEW) |

**Comment by christocracy** [comment]
>OkHTTP3

The Android library `tslocationmanager.aar` is actually compiled against `okhttp:4.9.1`.  You can control the version using `ext` vars in your `android/build.gradle` using [`okHttpVersion`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L56).  However, the next release of *Background Geolocation* will bump up the default to `4.9.1`.

```gradle
buildscript {
    ext {
        .
        .
        .
        okHttpVersion = "4.9.1"
    }
}
```

>GreenRobot EventBus

This cannot be controlled via `ext` vars.  `v3.2.0`.  The next next release will update to `3.2.0`.

> Android Permissions

I'm well aware of recent updates to this package and I periodically donate $ to the author of this package, [most recently a couple of weeks ago](https://github.com/nishkarsh/android-permissions/issues/20#issuecomment-883497520) in order to expedite migration from *jCenter* -> *MavenCentral*.  I know exactly what v2 provides and `BackgroundGeolocation` is perfectly happy at `0.1.8` for now.

> SLF4J

BackgroundGeolocation imports `slf4j` as a dependency of [`logback-android@2.0.0`](https://github.com/tony19/logback-android#quick-start) which requires `slf4j-api:1.7.25`.

![](https://dl.dropbox.com/s/fi6j0d9u3g1ieyr/Screen%20Shot%202021-08-02%20at%2010.17.40%20AM.png?dl=1)

**Comment by christocracy** [comment]
> OkHTTP3 | 3.12.1 | 3.14.9 (released 2020-05-17) however version 5 is in beta.

`okhttp > 3.x` requires `minSdkVersion 21` (*Android 5*).  Once you use `okHttp > 3`, your app will work only for *Android 5+*.

**Comment by grahamsmith** [comment]
That's interesting. To be honest I have a personal bias that pre 5 Android needs to die. We are at Android 12 and the mentality of supporting Android 4 released around 2013, nearly 8 years ago vs something like Windows 8 (2012-2016 4ish years) is not sustainable.

Would love to know market share of users who have purchased this SDK who are on pre 5. Do you know from any stats etc?

**Comment by christocracy** [comment]
You are free to adjust your own `minSdkVersion 21` and `okHttpVersion` as suits your own preferences.

I intend to have the sdk support Android 4+.

**Comment by grahamsmith** [comment]
Our current min is already 26. Out of interest how do you manage the different versions of OKHttp with their different implementations via setting a version in Gradle? Would have thought there were different implementations based on version in terms of SDK code. Or is it all the same until V5?

**Comment by christocracy** [comment]
This sdk uses only a small fraction of what okhttp offers.  The sdk is completely compatible with okhttp 4.9.1.

As i said, tslocationmanager.aar is compiled against okhttp:4.9.1.
