### ISSUE TITLE
how to create  a sample in background every 10 meters

### ISSUE THREAD

**Issue by daviddagan** [transistorsoft/flutter_background_geolocation#712]
If I want to execute my own function and save the result in the background, what should I do?
1. assign headless function
2. assign background fetch 
3. set headless mode: true?
if so, I still don't see it

**Comment by christocracy** [comment]
The issue template is *not* optional.

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
