### ISSUE TITLE
Information regarding heartbeat function 

### ISSUE THREAD

**Issue by sushrutnaik** [transistorsoft/flutter_background_geolocation#911]
bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
  print('[onHeartbeat] ${event}');

  // You could request a new location if you wish.
  bg.BackgroundGeolocation.getCurrentPosition(
    samples: 1,
    persist: true
  ).then((bg.Location location) {
   if(SharedPrefs().getIsLoggedIn()==true){
       // await Future.delayed(Duration(seconds: 5));
      controller.sendLocation(userController.user.value!.vehicleId!, location.coords.latitude, location.coords.longitude);
      }
  });
});

using this heartbeat function not send location even when app is killed in background heartbeat sound is coming but location is not updating

**Comment by christocracy** [comment]
The issue template is not optional, it’s required.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
