### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected 

### ISSUE THREAD

**Issue by klkucaj** [transistorsoft/flutter_background_geolocation#933]
Can someone help me with this?? 
_Android 11 (R)
API 30
Pixel 4_

```
D/FlutterGeolocator(12490): Attaching Geolocator to activity
D/FlutterGeolocator(12490): Creating service.
D/FlutterGeolocator(12490): Binding to location service.
E/AndroidRuntime(12490): FATAL EXCEPTION: main
E/AndroidRuntime(12490): Process: com.dashfuel.app, PID: 12490
E/AndroidRuntime(12490): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~KPtYTQeobzWgbpitvR1gRA==/com.dashfuel.app-6WlMr0kIASZp6YLXPNnv2g==/base.apk)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.location.TSLocationManager.removeLocationUpdates(Unknown Source:41)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stopUpdatingLocation(Unknown Source:0)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:0)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:100)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.adapter.TSConfig$c$a.a(Unknown Source:63)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.lifecycle.LifecycleManager.e(Unknown Source:39)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.lifecycle.LifecycleManager.onStart(Unknown Source:46)
E/AndroidRuntime(12490): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:39)
E/AndroidRuntime(12490): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
E/AndroidRuntime(12490): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
E/AndroidRuntime(12490): 	at com.transistorsoft.locationmanager.lifecycle.LifecycleManager.run(Unknown Source:8)
E/AndroidRuntime(12490): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(12490): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12490): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(12490): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(12490): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12490): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(12490): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by christocracy** [comment]
See the [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#482---2022-10-26) at v4.8.2:

>play-services:location has [introduced a breaking change](https://developers.google.com/android/guides/releases#october_13_2022) in v21, breaking the plugin. googlePlayServicesLocationVersion will be capped with a maximum of v20. The next major release (4.10.0) will set a minimum required version of v21.

You cannot use `googlePlayServicesLocationVersion` > 20.0.0.

**Comment by christocracy** [comment]
One of your *other* plugins *is*.

Run `./gradlew app:dependencies` to  see which:

```
$ cd android
$ ./gradlew  app:dependencies
```

**Comment by christocracy** [comment]
Also, you ignored the issue template, which asked you for the plugin version, among other things.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I can easily release a version compiled for `googlePlayServicesLocationVersion` >= `v21`.  But once I do, one will have to make sure all their other plugins importing `play-services-location` are compatible with `v21` as well.

**Comment by klkucaj** [comment]
@christocracy it was this package https://pub.dev/packages/geolocator/versions/8.2.1, i removed it because i dont need it anymore. Thank you! 

But since this thread is still open, i have an issue, i am not getting geofence callbacks, this is the code:
```
try {
      await bg.BackgroundGeolocation.removeListeners();
      bg.BackgroundGeolocation.onGeofence(_onGeofence);
      bg.State state = await bg.BackgroundGeolocation.ready(
        bg.Config(
          autoSync: true,
          geofenceModeHighAccuracy: true,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          debug: kDebugMode,
          logLevel: kDebugMode
              ? bg.Config.LOG_LEVEL_VERBOSE
              : bg.Config.LOG_LEVEL_OFF,
        ),
      );
      state = await bg.BackgroundGeolocation.startGeofences();
      debugPrint(
        "Geofence State Enabled: ${state.enabled} ${state.trackingMode}",
      );
    } catch (e) {
      debugPrint("Geofence init error: $e");
    }
```
I dont know if i am doing something wrong ?

**Comment by christocracy** [comment]
>java.lang.IncompatibleClassChangeError: Found interface

If you have an unrelated issue, post a new issue.  Do *not* ignore the issue template.

**Comment by ivangoluuk** [comment]
I ran the command  ./gradlew app:dependencies and got the following output

- project :flutter_background_geolocation
|    +--- com.transistorsoft:tslocationmanager:+ -> 3.2.10
|    +--- com.google.android.gms:play-services-location:20.0.0 (*)


- project :geolocator_android
|    +--- com.google.android.gms:play-services-location:20.0.0
|    |    +--- com.google.android.gms:play-services-base:18.0.1

both packages are using the same googlePlayServicesLocationVersion

**Comment by ivangoluuk** [comment]
search using this filter -> com.google.android.gms:play-services-location:21.0.0 and no results

**Comment by christocracy** [comment]
> search using this filter -> com.google.android.gms:play-services-location:21.0.0 and no results

That wouldn’t capture `21.0.1` (the latest version).

**Comment by Mmisiek** [comment]
I have same experience with plugin: 
`geolocator_android`

I resolved it by forcing:
`dependency_overrides:
  geolocator: 9.0.1
  geolocator_android: 4.1.4`

They changed to API 21 in version 4.1.7.

**Comment by christocracy** [comment]
Three days ago, the people over at `geolocator_android` [naively accepted a pull-request](https://github.com/Baseflow/flutter-geolocator/commit/b214430ad635cf802fdae84f2c96a49d861c05cf) bumping their [hard-coded `play-services:location` version](https://github.com/Baseflow/flutter-geolocator/commit/b214430ad635cf802fdae84f2c96a49d861c05cf) to `v21` and released it to a **point release** `4.1.6`, rather than a *major version* bump (eg: `4.2.0`).

I [let them know their causing havoc](https://github.com/Baseflow/flutter-geolocator/pull/1202#issuecomment-1406859865) at the pull-request where this change was accepted.

**Comment by Mmisiek** [comment]
Thanks @christocracy !

**Comment by christocracy** [comment]
I'll be releasing a `v4.9.0` here next week with `play-services:location @ `v21`.  it's not a difficult task and I've been aware of this [since October](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#482---2022-10-26)).  I just wasn't counting on it being forced upon me by some other plugin's point-release.

<img width="1158" alt="Screenshot 2023-01-29 at 6 25 47 PM" src="https://user-images.githubusercontent.com/14999/215362024-89397a90-11be-4138-82a8-88be9267294b.png">

It's just that when one does so, they'll have to make sure *all* their other modules using `play-services:location` are @ `v21+` as well (eg: map components, etc).

This all could have been avoided at `flutter_geolocator` had they implemented a *Gradle Configuration Variable* `ext.playServicesLocationVersion`, as done here, instead of a hard-coded version.

**Comment by juuzou12** [comment]
> geolocator_android

thank you for that i had to do a lot of research to know this

**Comment by christocracy** [comment]
I'm working on compiling two separate version of `tslocationmanager.aar` (one for `v20` and another for `v21`.

The plugin's `build.gradle` will detect your configured `ext.playServicesLocationVersion` and import the corresponding `tsloctionmanager.aar`.

**Comment by christocracy** [comment]
v4.9.0 is now released with play-services-location support for v21

**Comment by iulian0512** [comment]
> v4.9.0 is now released with play-services-location support for v21

my app still crashes with geolocator:9.0.2 and geolocator_android: 4.1.7 same exception

**Comment by christocracy** [comment]
Observe your `./gradlew app:dependencies`

**Comment by iulian0512** [comment]
> Observe your `./gradlew app:dependencies`

i forgot to set ext.playServicesLocationVersion in build.gradle, thanks for the quick reply.

**Comment by ahmednasser74** [comment]
I faced the same issue cause I upgraded geoLocator to v9.0.2  which uses googlePlayServicesLocationVersion v21 
and flutter_background_geolocation uses v20

So, **I solved it by downgrade geoLocator to v8.2.1** in pubspec.yaml

**Comment by christocracy** [comment]
4.9.0 now supports `ext.playServicesLocationVersion = “21.0.1”` in your android/build.gradle

**Comment by wmonecke** [comment]
@christocracy we recently bought your license and the lib performs great. we also use it in combination with maplibre and now encounter this error too.

<img width="358" alt="Screenshot 2024-11-26 at 19 07 29" src="https://github.com/user-attachments/assets/cd91f8e4-172a-4ce0-acc6-31f5f34e5d1f">

<img width="661" alt="image" src="https://github.com/user-attachments/assets/2bf5b7dd-e1a8-41d4-aff8-a8717f495998">

we added this in our android/app/build.gradle:
```bash
    implementation(project(path: ':maplibre_maplibre-react-native')) {
        exclude group: 'com.google.android.gms'
    }
```

we are still seeing this issue however. do you know what else we could try?

**Comment by christocracy** [comment]
>`com.google.android.gms.play-services-location:17.0.0`

LOL!  That version is from [2019](https://maven.google.com/web/index.html?q=location#com.google.android.gms:play-services-location:17.0.0)

See [maven.google.com](https://maven.google.com/web/index.html?q=location#com.google.android.gms:play-services-location)

You are forced to lower your [`ext.googlePlayServicesLocationVersion`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-AUTO.md#open_file_folder-androidbuildgradle) to that used by this `react-native-map-libre` because they don't provide any way to use a modern version of `play-services-location`.

Why are you posting a `react-native` issue at the **Flutter** version of background-geolocation?

**Comment by wmonecke** [comment]
@christocracy damn, I didnt realize this was the flutter repo. been banging my head against the wall on this one. Thanks for the reference.

**Comment by christocracy** [comment]
I suggest you consult with the maintainers of this `react-native-map-libre` and inform that they're using a version of `play-services-location` from the era of Android 10.

**Comment by christocracy** [comment]
Google Play Services is essentially Google's proprietary extensions to the Android OS.  When you use `play-services-location` from 4-5 years ago, you're implementing the Location API from that era, missing out on enhancements made for operating with modern devices.

**Comment by wmonecke** [comment]
Ah I see, thanks for the explanation! Will talk to the Maplibre team!
