### ISSUE TITLE
Android app crash on bg.BackgroundGeolocation.start() using flutter_background_geolocatio.

### ISSUE THREAD

**Issue by mnikam-unico** [transistorsoft/flutter_background_geolocation#960]
After allow all the location permissions app crash in flutter android app.I have licensed key.Previously its working fine but suddenly its crashes in android app.
code - 

  dynamic callback = (bg.State state) async {
        print('[start] success: $state');
      };
      bg.State state = await bg.BackgroundGeolocation.state;
      if (state.trackingMode == 1) {
       bg.BackgroundGeolocation.start().then(callback);
      } else {
        bg.BackgroundGeolocation.startGeofences().then(callback);
      }

![WhatsApp Image 2023-02-21 at 7 02 14 PM](https://user-images.githubusercontent.com/65884664/220358856-796fb6f3-f42b-4d7d-9c38-19776b6e3e7f.jpeg)

Error log
E/TSLocationManager(17397): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/org.hccts.brain-LtqBQK_70l3rJXtKAG0XBg==/base.apk!classes23.dex)
E/TSLocationManager(17397): 	at com.transistorsoft.locationmanager.location.SingleLocationRequest.finish(Unknown Source:39)
E/TSLocationManager(17397): 	at com.transistorsoft.locationmanager.location.TSLocationM

**Comment by christocracy** [comment]
The issue template is *not* optional, it's *required*.

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by Huge-Puppy** [comment]
@mnikam-unico  We had this error as well. The cause was in `android/build.gradle` we had to change `playServicesLocationVersion` to `"21.0.0"` instead of `"20.0.0"`. Try it out and let me know if it works.

**Comment by christocracy** [comment]
>we had to change playServicesLocationVersion to "21.0.0"

He **ignored** the issue template and didn't post the requested `Plugin version`.

`playServicesLocationVersion = "21.0.0" only works with the [latest version `4.9.0`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#490--2023-02-01).  It's **unknown** if he's using `4.9.0`.  He could be using `<= 4.8.7`.  We don't know.  One gets support much quicker when they don't  ignore the issue template.

The problem is **certainly** related to `playServicesLocationVersion`.
