### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by LuisEgusquiza** [transistorsoft/flutter_background_geolocation#964]
<meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

help please........

**Comment by LuisEgusquiza** [comment]
<meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>


help please........

**Comment by christocracy** [comment]
You really don't have a clue what you're doing.

**Comment by christocracy** [comment]
I don't think you're ready to be a mobile app developer.

**Comment by christocracy** [comment]
The issue template is *not* optional -- it's **required**

Closed for ignoring issue template


*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by LuisEgusquiza** [comment]
Sorry for my little experience.

I followed the documentation as is but it does not run the application
